# Keep all in alphabetical order
components:
  libs/hooks/open-telemetry:
    - beeme1mr
    - toddbaert
  libs/providers/config-cat:
    - lukas-reining
    - adams85
  libs/providers/config-cat-web:
    - lukas-reining
    - adams85
  libs/providers/env-var:
    - beeme1mr
    - toddbaert
  libs/providers/flagd:
    - beeme1mr
    - toddbaert
  libs/providers/flagd-web:
    - beeme1mr
    - toddbaert
  libs/providers/go-feature-flag:
    - thomaspoignant
  libs/providers/go-feature-flag-web:
    - thomaspoignant
  libs/providers/launchdarkly-client:
    - kinyoklion
    - mateoc
    - sago2k8
  libs/providers/flipt:
    - markphelps
  libs/providers/flipt-web:
    - markphelps

ignored-authors:
  - renovate-bot
