// Code generated by scripts/write-revision.js. DO NOT EDIT.
//
// Regenerate with `nx pullSpec tck`, which both checks out the
// open-feature/spec submodule and rewrites this file from it.

/** The open-feature/spec commit the conformance artifacts in `spec/` were taken from. */
export const SPEC_REVISION = 'bda599f1db440aa8d395d1d3af7b9b3cc3103b98';
