// Code generated by scripts/write-revision.js. DO NOT EDIT.
//
// Regenerate with `nx pullSpec tck`, which both checks out the
// open-feature/spec submodule and rewrites this file from it.

/** The open-feature/spec commit the conformance artifacts in `spec/` were taken from. */
export const SPEC_REVISION = 'aa2ad24f5a14ae2b5756df0b6d23f493f39507e6';
