import { LDLogger } from 'launchdarkly-js-client-sdk';

/**
 * Options for the {@link LaunchDarklyClientProvider}.
 */
export interface LaunchDarklyProviderOptions {
  /**
   * Configures a logger for warnings and errors generated by the provider.
   *
   * The logger can be any object that conforms to the `LDLogger` interface.
   * For a simple implementation that lets you filter by log level, see
   * `basicLogger`. You can also use an instance of `winston.Logger` from
   * the Winston logging package.
   *
   * If you do not set this property, the provider uses `basicLogger` with a
   * minimum level of `info`.
   *
   * By default this will not be the same logger instance used by the SDK.
   * If the provider should share a logger with the SDK, then you will need to
   * provide the logger in the SDK options as well.
   */
  logger?: LDLogger;
}
